<?xml version="1.0"?>
<!--
Copyright (c) 2024 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="base">
    <xacro:include filename="$(find s_description)/urdf/properties.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/caster.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/depthai_macro.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/inertials.xacro" />
    <xacro:include filename="$(find s_description)/urdf/ld06.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/material.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/wheel.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/oakd.urdf.xacro" />


    <link name="base_link">
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <origin rpy="0 0 0"
                xyz="${(-body_length/2)+wheel_offset_from_front} 0 ${(body_height/2)}" />
        </collision>
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}" />
            </geometry>
            <material name="aluminum_frame" />
            <origin rpy="0 0 0"
                xyz="${(-body_length/2)+wheel_offset_from_front} 0 ${(body_height/2)}" />
        </visual>
        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <mass value="12" />
            <inertia
                ixx="${(1/12) * mass * ((body_width  * body_width)  + (body_height * body_height))}"
                ixy="0.0" ixz="0.0"
                iyy="${(1/12) * mass * ((body_length * body_length) + (body_height * body_height))}"
                iyz="0.0"
                izz="${(1/12) * mass * ((body_length * body_length) + (body_width  * body_width))}" />
        </inertial>
    </link>
    <gazebo reference="base_link">
        <material>
            Gazebo/Grey
        </material>
    </gazebo>

    <link name="base_footprint" />

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_to_floor_z_offset}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <xacro:wheel
        side="left"
        radius="${wheel_radius}"
        width="${wheel_width}"
        pos_x="${wheel_pos_x}"
        pos_y="${wheel_pos_y}"
        pos_z="${wheel_pos_z}"
        mass="${wheel_mass}"
    />

    <xacro:wheel
        side="right"
        radius="${wheel_radius}"
        width="${wheel_width}"
        pos_x="${wheel_pos_x}"
        pos_y="${-wheel_pos_y}"
        pos_z="${wheel_pos_z}"
        mass="${wheel_mass}"
    />
    <xacro:caster_wheel
        side="front"
        mass="0.01"
    />

    <xacro:caster_wheel
        side="rear"
        mass="0.01"
    />

    <link name="scan" />
    <joint name="base_to_scan" type="fixed">
      <parent link="base_link" />
      <child link="scan" />
      <origin xyz="-0.018  -0.090 0.430" rpy="0 0 ${M_PI}" />
    </joint>
    <xacro:ld06 lidar_prefix="top_lidar">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:ld06>
    <joint name="base_to_lidar_frame_top_lidar" type="fixed">
      <parent link="scan" />
      <child link="lidar_frame_top_lidar" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <!-- <xacro:ld06 lidar_prefix="right_rear">
        <origin xyz="${-(body_length / 2) - 0.030}  -${((body_width / 2) - 0)} 0.200"
            rpy="0 0 ${M_PI}" />
    </xacro:ld06>

    <xacro:ld06 lidar_prefix="left_front">
        <origin xyz="${(body_length / 2) + 0.030}  ${((body_width / 2) - 0.0)} 0.040" rpy="0 0 0" />
    </xacro:ld06> -->

    <xacro:include filename="$(find s_description)/urdf/time_of_flight.urdf.xacro" />
    <xacro:include filename="$(find s_description)/urdf/sonar.urdf.xacro" />

    <xacro:diff_drive_controller
        wheel_separation="${wheel_pos_y * 2}"
        wheel_radius="${wheel_radius}"
    />

    <!-- <xacro:depthai_camera
        camera_name="oakd_left"
        camera_model="OAK-D"
        parent="base_link"
        base_frame="oakd_left_base_link"
        cam_pos_x="0.170"
        cam_pos_y="0.055"
        cam_pos_z="0.350"
        cam_roll="0.0"
        cam_pitch="0.0"
        cam_yaw="0.523599"
    />
    <xacro:depthai_camera
        camera_name="oakd_right"
        camera_model="OAK-D"
        parent="base_link"
        base_frame="oakd_right_base_link"
        cam_pos_x="0.170"
        cam_pos_y="-0.055"
        cam_pos_z="0.350"
        cam_roll="0.0"
        cam_pitch="0.0"
        cam_yaw="-0.523599"
    /> -->

    <xacro:oakd_link mount_point="right" />
    <xacro:oakd_joint mount_point="right">
        <origin xyz="0.170 -0.055 0.350" rpy="0 0 -0.523599" />
    </xacro:oakd_joint>
    <link name="oakd_left_right_camera_optical_frame" />
    <joint name="oakd_left_link_optical_frame" type="fixed">
        <parent link="oakd_left"/>
        <child link="oakd_left_right_camera_optical_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
    <xacro:oakd_link mount_point="left" />
    <xacro:oakd_joint mount_point="left">
        <origin xyz="0.170 0.055 0.350" rpy="0 0 0.523599" />
    </xacro:oakd_joint>
    <link name="oakd_right_right_camera_optical_frame" />
    <joint name="oakd_right_link_optical_frame" type="fixed">
        <parent link="oakd_right"/>
        <child link="oakd_right_right_camera_optical_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
</robot>