<?xml version="1.0"?>
<!--
Copyright (c) 2023 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:macro name="caster_wheel" params="side mass">
		<xacro:property name="caster_wheel_radius" value="0.0381" />
		<xacro:if value="${side == 'front'}">
			<xacro:property name="caster_wheel_x" value="${fwheel_offset}" />
		</xacro:if>

		<xacro:if value="${side == 'rear'}">
			<xacro:property name="caster_wheel_x" value="${-fwheel_offset}" />
		</xacro:if>

		<link name="${side}_caster_wheel_link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<sphere radius="${caster_wheel_radius}" />
				</geometry>
				<material name="red">
					<color rgba="0.416 0.051 0.047 1.0" />
				</material>
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<sphere radius="${caster_wheel_radius}" />
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<mass value="${mass}" />
				<inertia ixx="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" ixy="0"
					ixz="0"
					iyy="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" iyz="0"
					izz="${(2/5) * mass * (caster_wheel_radius * caster_wheel_radius)}" />
			</inertial>
		</link>

		<gazebo reference="${side}_caster_wheel_link">
			<mu1>0.01</mu1>
			<mu2>0.01</mu2>
			<material>Gazebo/Red</material>
		</gazebo>

		<joint name="${side}_caster_wheel_joint" type="fixed">
			<parent link="base_link" />
			<child link="${side}_caster_wheel_link" />
			<origin
				xyz="${caster_wheel_x} 0 -${wheel_radius + gear_box_center_height - caster_wheel_radius}"
				rpy="0 0 0" />
		</joint>
	</xacro:macro>
</robot>