<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- This first link called "world" is empty -->
  <!-- <link name="world"></link> -->

  <!-- A simple fixed joint from our empty world link, to our base. -->
  <!-- The base origin is offset from the world origin. -->
  <!-- <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 -0.541 0" />
    <parent link="world" />
    <child link="odom" />
  </joint> -->

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <argument>odom:=odom_unfiltered</argument>
      </ros>
      <updateRate>100</updateRate>
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <wheel_separation>${body_width * (2 * wheel_center_offset)}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <robot_base_frame>base_footprint</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
  </plugin>
  </gazebo>


</robot>